#!/bin/bash
# Script to configure S3 bucket for static website hosting
# This fixes the 403 error when accessing routes directly
#
# Usage: ./scripts/configure-s3-website.sh YOUR_BUCKET_NAME

set -e

BUCKET_NAME=$1

if [ -z "$BUCKET_NAME" ]; then
  echo "Error: Please provide your S3 bucket name"
  echo "Usage: ./scripts/configure-s3-website.sh YOUR_BUCKET_NAME"
  exit 1
fi

echo "Configuring S3 bucket '$BUCKET_NAME' for static website hosting..."

# Enable static website hosting
# IMPORTANT: Use 404.html as error document (not index.html)
# 404.html is generated by Next.js and handles client-side routing
aws s3 website s3://$BUCKET_NAME \
  --index-document index.html \
  --error-document 404.html

echo "✅ Static website hosting configured!"
echo ""
echo "Configuration:"
echo "  - Index document: index.html"
echo "  - Error document: index.html"
echo ""
echo "Your website endpoint should be:"
echo "  http://$BUCKET_NAME.s3-website-$(aws configure get region).amazonaws.com"
echo ""
echo "⚠️  Important: If you're using CloudFront, make sure it points to the"
echo "   website endpoint (not the bucket endpoint)!"

